### ISSUE TITLE
Cannot find module '@nodegui/svelte-nodegui' or its corresponding type declarations.

### ISSUE THREAD

**Issue by mbykov** [nodegui/svelte-nodegui-starter#6] opened 2021-08-09 09:37 UTC
From the very scratch:
npx degit ....
npm run dev

> svelte-nodegui-starter@1.0.2 dev
> webpack --mode=development

assets by status 58.1 KiB [cached] 1 asset
asset nodegui_core-71e80e7a0d4c8202eac6ca8d0e0c6d25.node 7.41 MiB [compared for emit] (auxiliary name: main)
asset index.js 1.39 MiB [compared for emit] (name: main) 1 related asset
runtime modules 21.9 KiB 10 modules
modules by path ./node_modules/@nodegui/nodegui/ 510 KiB 212 modules
modules by path ./node_modules/postcss/lib/*.js 479 KiB 25 modules
modules by path ./node_modules/source-map/ 99.4 KiB 11 modules
modules by path ./src/ 10.8 KiB
  modules by path ./src/components/ 6.85 KiB 3 modules
  2 modules
modules by path ./node_modules/cuid/ 2.88 KiB 4 modules
modules by path ./node_modules/webpack/hot/*.js 3.75 KiB 3 modules
modules by path ./node_modules/chalk/ 12.1 KiB 3 modules
modules by path ./node_modules/color-convert/*.js 20.3 KiB 3 modules
modules by path ./node_modules/svelte/ 54.1 KiB
  ./node_modules/svelte/internal/index.mjs 53.9 KiB [built] [code generated]
  ./node_modules/svelte/index.mjs 212 bytes [built] [code generated]
18 modules

ERROR in ./src/app.ts 1:0-56
Module not found: Error: Can't resolve '@nodegui/svelte-nodegui' in '/home/michael/d-nodegui/sns/src'

...

etc

what does this mean?

what should be done?

**Comment by IDmedia** [comment] 2021-08-25 18:46
Try to run:
```npm i @nodegui/svelte-nodegui```

**Comment by mbykov** [comment] 2021-08-26 08:45
Yes, thank you. Now it works, but Gui is messed up. 

I hope this project is alive and we will see new versions

**Comment by IDmedia** [comment] 2021-08-26 08:47
Yeah, I just found this project myself and had the same issue as you.
GUI broken here too so I think I'll find another framework for now.

**Comment by clozach** [comment] 2021-09-09 19:25
For the record, here's how it's rendering for me in macOS 11.5.1 (Big Sur).

![image](https://user-images.githubusercontent.com/124952/132749968-bd4ff0d3-1ecf-4c63-9bcd-bdaefa491b84.png)

**Comment by milahu** [comment] 2021-09-17 18:58
package-lock.json is old

```
    "@nodegui/svelte-nodegui": {
      "version": "0.1.1",
```

should be 0.1.2

**Comment by shirakaba** [comment] 2021-12-27 22:15
This issue is a duplicate of https://github.com/nodegui/svelte-nodegui/issues/67.

As for the layout issue, moving discussion to https://github.com/nodegui/svelte-nodegui/issues/72.

**Closed as completed by shirakaba** 2021-12-27 22:15 UTC
